apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: h90f26bw0-python-gitops
  description: This is GitOps manifest for h90f26bw0-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=h90f26bw0-python
    backstage.io/kubernetes-id: h90f26bw0-python 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: h90f26bw0-python
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:h90f26bw0-python
