apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: h90f26bw0-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: artifactory-docker-artifactory-jcr.apps.rosa.rhtap-services.xmdt.p3.openshiftapps.com/rhtap/rhtap-qe-python:aec5ee3ac69b027fcd5f29dc3f7ff1e4fe1458a3@sha256:090d87f8ea1b9b1c5ee62ae5e4d8ab1f9a47ae39f22351b6bc1e0bcb0e4f890b
          name: container-image
